### ISSUE TITLE
wakeonlan not working after creating inventory

### ISSUE THREAD

**Issue by Wurzelmann** [crombeen/ansible#1]
Hi,

first of all, thank you for this great collection, this is a good place to start for anyone seeking ansible workflows. :-)

I've tried your collect and wakeonlan playbooks and I get a systems.csv with data, but I do not understand, how the wakeonlan playbook should be able to wake up the machines from the systems.csv file... I only get

    FAILED! => {"msg": "The task includes an option with an undefined variable. The error was: {{ (ansible_interfaces|first).macaddress|default(mac|default('')) }}: 'ansible_interfaces' is undefined

Am I doing something wrong?

**Comment by Deonicei** [comment]
Hi, i tried to do the same thing. Here`s what u need:

Assuming u have a valid inventory file (`hosts` for me), and added to your `ansible.cfg`, you can add mac addresses to hosts like this:

```
[example]
laptop ansible_host=192.168.0.100 mac=xx:yy:zz:aa:bb:cc
```
After that, the mac addresses as variable can be accessed:

```
vars:
    macaddr: "{{ hostvars['example'].macaddress|default(mac|default('')) }}"
tasks:
    - name: Send WakeOnLan
      community.general.wakeonlan:
        mac: '{{ macaddr }}'
      delegate_to: localhost
```

Not sure how it was supposed to work initially, but at least this config worked for me (checked only on one host). This thread helped: [Accessing inventory host variable in Ansible playbook](https://stackoverflow.com/a/49450361)
